# Generated by Django 5.0.6 on 2024-06-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('given', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='wri_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
